---
title: "Practica 2"
author: "Daniel Afonso González"
date: "24 de diciembre de 2018"
output: pdf_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Descripción del dataset. ¿Por qué es importante y qué pregunta/problema pretende responder?
# Integración y selección de los datos de interés a analizar.
# Limpieza de los datos.
## ¿Los datos contienen ceros o elementos vacíos? ¿Cómo gestionarías cada uno
de estos casos?
## Identificación y tratamiento de valores extremos.
# Análisis de los datos.
## Selección de los grupos de datos que se quieren analizar/comparar (planificación de los análisis a aplicar).
## Comprobación de la normalidad y homogeneidad de la varianza.
## Aplicación de pruebas estadísticas para comparar los grupos de datos.
En función de los datos y el objetivo del estudio, aplicar pruebas de contraste de hipótesis, correlaciones, regresiones, etc.
# Representación de los resultados a partir de tablas y gráficas.
# Resolución del problema.
A partir de los resultados obtenidos, ¿cuáles son las conclusiones? ¿Los resultados permiten responder al problema?
